"""function generate_unique_code()

Revision ID: 03579709be2e
Revises: 23049459f0f7
Create Date: 2025-01-19 15:56:30.138279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03579709be2e'
down_revision = '23049459f0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['recovery_pin'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
