"""Add is_verified field to User

Revision ID: 11625bddb89d
Revises: e341bda8c625
Create Date: 2025-01-05 16:16:37.022753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11625bddb89d'
down_revision = 'e341bda8c625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('verification_code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('verification_code',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###
