"""Add PIN code model

Revision ID: 23049459f0f7
Revises: 9256cc4db064
Create Date: 2025-01-19 00:55:03.104411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23049459f0f7'
down_revision = '9256cc4db064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('recovery_pin', sa.String(length=6), nullable=True))

    # Asignar un PIN temporal a todas las filas existentes
    from app.models import User
    import random
    import string
    from sqlalchemy.orm import Session
    from sqlalchemy import select

    bind = op.get_bind()
    session = Session(bind=bind)

    # Generar y asignar un PIN único para cada usuario existente
    users = session.execute(select(User)).scalars().all()
    for user in users:
        user.recovery_pin = ''.join(random.choices(string.digits, k=6))
        session.add(user)

    session.commit()

    # Hacer que la columna sea NOT NULL después de asignar los valores
    op.alter_column('user', 'recovery_pin', nullable=False)


    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('recovery_pin')

    # ### end Alembic commands ###
