"""Add PasswordRecoveryRequest model

Revision ID: 85f23b1ebe71
Revises: ca28bf3e410c
Create Date: 2025-01-18 22:09:48.521844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f23b1ebe71'
down_revision = 'ca28bf3e410c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_recovery_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_attempt', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_recovery_request')
    # ### end Alembic commands ###
