"""Add PasswordRecoveryAttempt model

Revision ID: 9256cc4db064
Revises: f27b2b777448
Create Date: 2025-01-18 23:17:07.388931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9256cc4db064'
down_revision = 'f27b2b777448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_recovery_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_column('attempt_count')
        batch_op.drop_column('last_attempt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_recovery_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_attempt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
