"""cambiar codigo a 6 dijistos

Revision ID: ca28bf3e410c
Revises: 11625bddb89d
Create Date: 2025-01-05 18:10:47.986131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca28bf3e410c'
down_revision = '11625bddb89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('verification_code',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('verification_code',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
