"""Add PasswordRecoveryRequest model

Revision ID: f27b2b777448
Revises: 85f23b1ebe71
Create Date: 2025-01-18 22:46:48.702595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f27b2b777448'
down_revision = '85f23b1ebe71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_recovery_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_attempt', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('password_recovery_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_recovery_request',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_attempt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='password_recovery_request_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='password_recovery_request_pkey')
    )
    op.drop_table('password_recovery_attempt')
    # ### end Alembic commands ###
